### ISSUE TITLE
No main generated

### ISSUE THREAD

**Issue by s1monw1** [hhariri/mark-code#2]
The following adoc-example will not be wrapped in a main:

```
[source,kotlin]
----
fun myMethod(notOptional: String, optional: String = "defaultValForOptionalString"){
    println("myMethod called with $notOptional and $optional")
}

//Possible Calls
myMethod("arg1", "arg2")
myMethod("arg1")
----
```

Trying to verify will lead to an error: No 'main' function in ...kt

Another example: 

```
[source,kotlin]
----
data class Person(val name: String, val age: Int, val job: String)
----
```

Does it have to be excluded explicitly?

Kind regards
simon

**Comment by hhariri** [comment]
Actually the README is incorrect. I'm going to update it. For the main to appear you need to verify using >>>
